# action.yml
name: 'Tag/Release on Push Action'
description: 'Creates a Tag/Release on pushes to a branch'
author: 'rymndhng'
inputs:
  bump_version_scheme:
    description: 'The versioning scheme to use for tags. One of: minor, major, patch'
    required: true
    default: 'minor'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'award'
  color: 'blue'
