name: Tests
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up BATS
        run: sudo npm install -g bats

      - name: Unit Tests
        run: make test

      - name: Integration Tests
        uses: rymndhng/release-on-push-action@${{ github.sha }}
        env:
          DRYRUN: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: true
